version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: user_service_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - user_service_network

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_service_app
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - user_service_network

networks:
  user_service_network:
    driver: bridge

volumes:
  postgres_data:
