name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: user-service-challenge
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Decode Service Account Key
        run: echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | base64 --decode > $HOME/gcloud-service-key.json

      - name: Authenticate to Google Cloud
        run: gcloud auth activate-service-account --key-file=$HOME/gcloud-service-key.json

      - name: Set Google Cloud Project
        run: gcloud config set project user-service-challenge

      - name: Set Google Cloud Region
        run: gcloud config set run/region us-central1

      - name: Enable Required APIs
        run: |
          gcloud services enable cloudbuild.googleapis.com \
          artifactregistry.googleapis.com \
          run.googleapis.com

      - name: Create Artifact Registry Repository (if not exists)
        run: |
          gcloud artifacts repositories create cloud-run-source-deploy \
          --repository-format=docker \
          --location=us-central1 \
          --description="Repository for Cloud Run deployments" || echo "Repository already exists."

      - name: Assign IAM Permissions to Service Account
        run: |
          gcloud projects add-iam-policy-binding user-service-challenge \
            --member="serviceAccount:github-deploy-service-account@user-service-challenge.iam.gserviceaccount.com" \
            --role="roles/artifactregistry.reader" || echo "Already has permissions."

          gcloud projects add-iam-policy-binding user-service-challenge \
            --member="serviceAccount:github-deploy-service-account@user-service-challenge.iam.gserviceaccount.com" \
            --role="roles/cloudbuild.builds.editor" || echo "Already has permissions."

          gcloud projects add-iam-policy-binding user-service-challenge \
            --member="serviceAccount:github-deploy-service-account@user-service-challenge.iam.gserviceaccount.com" \
            --role="roles/run.admin" || echo "Already has permissions."

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy user-service-challenge \
            --source . \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 8080 \
            --set-env-vars DATABASE_HOST=${{ secrets.DATABASE_HOST }},DATABASE_PORT=${{ secrets.DATABASE_PORT }},DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }},DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }},DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
            --cpu 1 \
            --memory 512Mi \
            --timeout 600s \
            --max-instances 3

      - name: Cleanup Service Account Key
        run: rm $HOME/gcloud-service-key.json
